/**
 */
package UnifiedMetamodel_.provider;

import UnifiedMetamodel_.util.UnifiedMetamodel_AdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class UnifiedMetamodel_ItemProviderAdapterFactory extends UnifiedMetamodel_AdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public UnifiedMetamodel_ItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Ejb} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EjbItemProvider ejbItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Ejb}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEjbAdapter() {
		if (ejbItemProvider == null) {
			ejbItemProvider = new EjbItemProvider(this);
		}

		return ejbItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.LayerSegment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LayerSegmentItemProvider layerSegmentItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.LayerSegment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLayerSegmentAdapter() {
		if (layerSegmentItemProvider == null) {
			layerSegmentItemProvider = new LayerSegmentItemProvider(this);
		}

		return layerSegmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Dto} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DtoItemProvider dtoItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Dto}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDtoAdapter() {
		if (dtoItemProvider == null) {
			dtoItemProvider = new DtoItemProvider(this);
		}

		return dtoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Store} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StoreItemProvider storeItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Store}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStoreAdapter() {
		if (storeItemProvider == null) {
			storeItemProvider = new StoreItemProvider(this);
		}

		return storeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.UI} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UIItemProvider uiItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.UI}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUIAdapter() {
		if (uiItemProvider == null) {
			uiItemProvider = new UIItemProvider(this);
		}

		return uiItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Layer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LayerItemProvider layerItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Layer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLayerAdapter() {
		if (layerItemProvider == null) {
			layerItemProvider = new LayerItemProvider(this);
		}

		return layerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.RestEntity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RestEntityItemProvider restEntityItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.RestEntity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRestEntityAdapter() {
		if (restEntityItemProvider == null) {
			restEntityItemProvider = new RestEntityItemProvider(this);
		}

		return restEntityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Facade} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FacadeItemProvider facadeItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Facade}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFacadeAdapter() {
		if (facadeItemProvider == null) {
			facadeItemProvider = new FacadeItemProvider(this);
		}

		return facadeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.War} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WarItemProvider warItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.War}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWarAdapter() {
		if (warItemProvider == null) {
			warItemProvider = new WarItemProvider(this);
		}

		return warItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Component} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComponentItemProvider componentItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Component}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComponentAdapter() {
		if (componentItemProvider == null) {
			componentItemProvider = new ComponentItemProvider(this);
		}

		return componentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.RelationArch} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RelationArchItemProvider relationArchItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.RelationArch}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRelationArchAdapter() {
		if (relationArchItemProvider == null) {
			relationArchItemProvider = new RelationArchItemProvider(this);
		}

		return relationArchItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.ArquitectureMetamodel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArquitectureMetamodelItemProvider arquitectureMetamodelItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.ArquitectureMetamodel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArquitectureMetamodelAdapter() {
		if (arquitectureMetamodelItemProvider == null) {
			arquitectureMetamodelItemProvider = new ArquitectureMetamodelItemProvider(this);
		}

		return arquitectureMetamodelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Containers} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContainersItemProvider containersItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Containers}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContainersAdapter() {
		if (containersItemProvider == null) {
			containersItemProvider = new ContainersItemProvider(this);
		}

		return containersItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Pojo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PojoItemProvider pojoItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Pojo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPojoAdapter() {
		if (pojoItemProvider == null) {
			pojoItemProvider = new PojoItemProvider(this);
		}

		return pojoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Services} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServicesItemProvider servicesItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Services}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServicesAdapter() {
		if (servicesItemProvider == null) {
			servicesItemProvider = new ServicesItemProvider(this);
		}

		return servicesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Metamodel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MetamodelItemProvider metamodelItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Metamodel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMetamodelAdapter() {
		if (metamodelItemProvider == null) {
			metamodelItemProvider = new MetamodelItemProvider(this);
		}

		return metamodelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Read} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReadItemProvider readItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Read}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReadAdapter() {
		if (readItemProvider == null) {
			readItemProvider = new ReadItemProvider(this);
		}

		return readItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Create} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CreateItemProvider createItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Create}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCreateAdapter() {
		if (createItemProvider == null) {
			createItemProvider = new CreateItemProvider(this);
		}

		return createItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Sale} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SaleItemProvider saleItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Sale}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSaleAdapter() {
		if (saleItemProvider == null) {
			saleItemProvider = new SaleItemProvider(this);
		}

		return saleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Exchange} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExchangeItemProvider exchangeItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Exchange}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExchangeAdapter() {
		if (exchangeItemProvider == null) {
			exchangeItemProvider = new ExchangeItemProvider(this);
		}

		return exchangeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Composition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompositionItemProvider compositionItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Composition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompositionAdapter() {
		if (compositionItemProvider == null) {
			compositionItemProvider = new CompositionItemProvider(this);
		}

		return compositionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Operations} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperationsItemProvider operationsItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Operations}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperationsAdapter() {
		if (operationsItemProvider == null) {
			operationsItemProvider = new OperationsItemProvider(this);
		}

		return operationsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Module} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModuleItemProvider moduleItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Module}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModuleAdapter() {
		if (moduleItemProvider == null) {
			moduleItemProvider = new ModuleItemProvider(this);
		}

		return moduleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.SpecialEntity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpecialEntityItemProvider specialEntityItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.SpecialEntity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpecialEntityAdapter() {
		if (specialEntityItemProvider == null) {
			specialEntityItemProvider = new SpecialEntityItemProvider(this);
		}

		return specialEntityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.GeneralEntity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GeneralEntityItemProvider generalEntityItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.GeneralEntity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGeneralEntityAdapter() {
		if (generalEntityItemProvider == null) {
			generalEntityItemProvider = new GeneralEntityItemProvider(this);
		}

		return generalEntityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Entity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntityItemProvider entityItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Entity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntityAdapter() {
		if (entityItemProvider == null) {
			entityItemProvider = new EntityItemProvider(this);
		}

		return entityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.RelationDom} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RelationDomItemProvider relationDomItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.RelationDom}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRelationDomAdapter() {
		if (relationDomItemProvider == null) {
			relationDomItemProvider = new RelationDomItemProvider(this);
		}

		return relationDomItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Transaction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TransactionItemProvider transactionItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Transaction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTransactionAdapter() {
		if (transactionItemProvider == null) {
			transactionItemProvider = new TransactionItemProvider(this);
		}

		return transactionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Submodule} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubmoduleItemProvider submoduleItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Submodule}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubmoduleAdapter() {
		if (submoduleItemProvider == null) {
			submoduleItemProvider = new SubmoduleItemProvider(this);
		}

		return submoduleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.DomainMetamodel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainMetamodelItemProvider domainMetamodelItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.DomainMetamodel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDomainMetamodelAdapter() {
		if (domainMetamodelItemProvider == null) {
			domainMetamodelItemProvider = new DomainMetamodelItemProvider(this);
		}

		return domainMetamodelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.ActionDispatcher} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActionDispatcherItemProvider actionDispatcherItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.ActionDispatcher}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createActionDispatcherAdapter() {
		if (actionDispatcherItemProvider == null) {
			actionDispatcherItemProvider = new ActionDispatcherItemProvider(this);
		}

		return actionDispatcherItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Router} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RouterItemProvider routerItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Router}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRouterAdapter() {
		if (routerItemProvider == null) {
			routerItemProvider = new RouterItemProvider(this);
		}

		return routerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.JSON} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JSONItemProvider jsonItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.JSON}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJSONAdapter() {
		if (jsonItemProvider == null) {
			jsonItemProvider = new JSONItemProvider(this);
		}

		return jsonItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.MD} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MDItemProvider mdItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.MD}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMDAdapter() {
		if (mdItemProvider == null) {
			mdItemProvider = new MDItemProvider(this);
		}

		return mdItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.CSS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CSSItemProvider cssItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.CSS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCSSAdapter() {
		if (cssItemProvider == null) {
			cssItemProvider = new CSSItemProvider(this);
		}

		return cssItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.APICall} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected APICallItemProvider apiCallItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.APICall}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAPICallAdapter() {
		if (apiCallItemProvider == null) {
			apiCallItemProvider = new APICallItemProvider(this);
		}

		return apiCallItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Directory} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DirectoryItemProvider directoryItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Directory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDirectoryAdapter() {
		if (directoryItemProvider == null) {
			directoryItemProvider = new DirectoryItemProvider(this);
		}

		return directoryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.State} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StateItemProvider stateItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.State}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStateAdapter() {
		if (stateItemProvider == null) {
			stateItemProvider = new StateItemProvider(this);
		}

		return stateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.UIFront} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UIFrontItemProvider uiFrontItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.UIFront}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUIFrontAdapter() {
		if (uiFrontItemProvider == null) {
			uiFrontItemProvider = new UIFrontItemProvider(this);
		}

		return uiFrontItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Visualizer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VisualizerItemProvider visualizerItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Visualizer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVisualizerAdapter() {
		if (visualizerItemProvider == null) {
			visualizerItemProvider = new VisualizerItemProvider(this);
		}

		return visualizerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Design} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DesignItemProvider designItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Design}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDesignAdapter() {
		if (designItemProvider == null) {
			designItemProvider = new DesignItemProvider(this);
		}

		return designItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.ActionCreator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActionCreatorItemProvider actionCreatorItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.ActionCreator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createActionCreatorAdapter() {
		if (actionCreatorItemProvider == null) {
			actionCreatorItemProvider = new ActionCreatorItemProvider(this);
		}

		return actionCreatorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.RouterComponent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RouterComponentItemProvider routerComponentItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.RouterComponent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRouterComponentAdapter() {
		if (routerComponentItemProvider == null) {
			routerComponentItemProvider = new RouterComponentItemProvider(this);
		}

		return routerComponentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Container} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContainerItemProvider containerItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Container}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContainerAdapter() {
		if (containerItemProvider == null) {
			containerItemProvider = new ContainerItemProvider(this);
		}

		return containerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.ServicesFront} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServicesFrontItemProvider servicesFrontItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.ServicesFront}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServicesFrontAdapter() {
		if (servicesFrontItemProvider == null) {
			servicesFrontItemProvider = new ServicesFrontItemProvider(this);
		}

		return servicesFrontItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Functionality} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionalityItemProvider functionalityItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Functionality}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionalityAdapter() {
		if (functionalityItemProvider == null) {
			functionalityItemProvider = new FunctionalityItemProvider(this);
		}

		return functionalityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.JS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JSItemProvider jsItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.JS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJSAdapter() {
		if (jsItemProvider == null) {
			jsItemProvider = new JSItemProvider(this);
		}

		return jsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Action} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActionItemProvider actionItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Action}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createActionAdapter() {
		if (actionItemProvider == null) {
			actionItemProvider = new ActionItemProvider(this);
		}

		return actionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Redux} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReduxItemProvider reduxItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Redux}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReduxAdapter() {
		if (reduxItemProvider == null) {
			reduxItemProvider = new ReduxItemProvider(this);
		}

		return reduxItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.ReactApp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReactAppItemProvider reactAppItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.ReactApp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReactAppAdapter() {
		if (reactAppItemProvider == null) {
			reactAppItemProvider = new ReactAppItemProvider(this);
		}

		return reactAppItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.File} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FileItemProvider fileItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.File}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFileAdapter() {
		if (fileItemProvider == null) {
			fileItemProvider = new FileItemProvider(this);
		}

		return fileItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.ComponentFront} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComponentFrontItemProvider componentFrontItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.ComponentFront}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComponentFrontAdapter() {
		if (componentFrontItemProvider == null) {
			componentFrontItemProvider = new ComponentFrontItemProvider(this);
		}

		return componentFrontItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Reducer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReducerItemProvider reducerItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Reducer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReducerAdapter() {
		if (reducerItemProvider == null) {
			reducerItemProvider = new ReducerItemProvider(this);
		}

		return reducerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.ModuleFront} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModuleFrontItemProvider moduleFrontItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.ModuleFront}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModuleFrontAdapter() {
		if (moduleFrontItemProvider == null) {
			moduleFrontItemProvider = new ModuleFrontItemProvider(this);
		}

		return moduleFrontItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.TechnologyMetamodel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TechnologyMetamodelItemProvider technologyMetamodelItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.TechnologyMetamodel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTechnologyMetamodelAdapter() {
		if (technologyMetamodelItemProvider == null) {
			technologyMetamodelItemProvider = new TechnologyMetamodelItemProvider(this);
		}

		return technologyMetamodelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.JavaApp} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JavaAppItemProvider javaAppItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.JavaApp}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJavaAppAdapter() {
		if (javaAppItemProvider == null) {
			javaAppItemProvider = new JavaAppItemProvider(this);
		}

		return javaAppItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.JEE_Project} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JEE_ProjectItemProvider jeE_ProjectItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.JEE_Project}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJEE_ProjectAdapter() {
		if (jeE_ProjectItemProvider == null) {
			jeE_ProjectItemProvider = new JEE_ProjectItemProvider(this);
		}

		return jeE_ProjectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.NativeClass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NativeClassItemProvider nativeClassItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.NativeClass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNativeClassAdapter() {
		if (nativeClassItemProvider == null) {
			nativeClassItemProvider = new NativeClassItemProvider(this);
		}

		return nativeClassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.EInterface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EInterfaceItemProvider eInterfaceItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.EInterface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEInterfaceAdapter() {
		if (eInterfaceItemProvider == null) {
			eInterfaceItemProvider = new EInterfaceItemProvider(this);
		}

		return eInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Library} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LibraryItemProvider libraryItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Library}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLibraryAdapter() {
		if (libraryItemProvider == null) {
			libraryItemProvider = new LibraryItemProvider(this);
		}

		return libraryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Attribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeItemProvider attributeItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Attribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeAdapter() {
		if (attributeItemProvider == null) {
			attributeItemProvider = new AttributeItemProvider(this);
		}

		return attributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.GenericClass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GenericClassItemProvider genericClassItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.GenericClass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGenericClassAdapter() {
		if (genericClassItemProvider == null) {
			genericClassItemProvider = new GenericClassItemProvider(this);
		}

		return genericClassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.MethodBack} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MethodBackItemProvider methodBackItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.MethodBack}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMethodBackAdapter() {
		if (methodBackItemProvider == null) {
			methodBackItemProvider = new MethodBackItemProvider(this);
		}

		return methodBackItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.AbstractClass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AbstractClassItemProvider abstractClassItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.AbstractClass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAbstractClassAdapter() {
		if (abstractClassItemProvider == null) {
			abstractClassItemProvider = new AbstractClassItemProvider(this);
		}

		return abstractClassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Epackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EpackageItemProvider epackageItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Epackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEpackageAdapter() {
		if (epackageItemProvider == null) {
			epackageItemProvider = new EpackageItemProvider(this);
		}

		return epackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.EClass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EClassItemProvider eClassItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.EClass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEClassAdapter() {
		if (eClassItemProvider == null) {
			eClassItemProvider = new EClassItemProvider(this);
		}

		return eClassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Annotation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AnnotationItemProvider annotationItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Annotation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAnnotationAdapter() {
		if (annotationItemProvider == null) {
			annotationItemProvider = new AnnotationItemProvider(this);
		}

		return annotationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Subproject} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubprojectItemProvider subprojectItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Subproject}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubprojectAdapter() {
		if (subprojectItemProvider == null) {
			subprojectItemProvider = new SubprojectItemProvider(this);
		}

		return subprojectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Descriptor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DescriptorItemProvider descriptorItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Descriptor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDescriptorAdapter() {
		if (descriptorItemProvider == null) {
			descriptorItemProvider = new DescriptorItemProvider(this);
		}

		return descriptorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.JavaScript} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JavaScriptItemProvider javaScriptItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.JavaScript}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJavaScriptAdapter() {
		if (javaScriptItemProvider == null) {
			javaScriptItemProvider = new JavaScriptItemProvider(this);
		}

		return javaScriptItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Util} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UtilItemProvider utilItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Util}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUtilAdapter() {
		if (utilItemProvider == null) {
			utilItemProvider = new UtilItemProvider(this);
		}

		return utilItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Reducers} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReducersItemProvider reducersItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Reducers}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReducersAdapter() {
		if (reducersItemProvider == null) {
			reducersItemProvider = new ReducersItemProvider(this);
		}

		return reducersItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Actions} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActionsItemProvider actionsItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Actions}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createActionsAdapter() {
		if (actionsItemProvider == null) {
			actionsItemProvider = new ActionsItemProvider(this);
		}

		return actionsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Back} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BackItemProvider backItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Back}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBackAdapter() {
		if (backItemProvider == null) {
			backItemProvider = new BackItemProvider(this);
		}

		return backItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Front} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FrontItemProvider frontItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Front}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFrontAdapter() {
		if (frontItemProvider == null) {
			frontItemProvider = new FrontItemProvider(this);
		}

		return frontItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.Property} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PropertyItemProvider propertyItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.Property}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPropertyAdapter() {
		if (propertyItemProvider == null) {
			propertyItemProvider = new PropertyItemProvider(this);
		}

		return propertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link UnifiedMetamodel_.AbstractMethod} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AbstractMethodItemProvider abstractMethodItemProvider;

	/**
	 * This creates an adapter for a {@link UnifiedMetamodel_.AbstractMethod}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAbstractMethodAdapter() {
		if (abstractMethodItemProvider == null) {
			abstractMethodItemProvider = new AbstractMethodItemProvider(this);
		}

		return abstractMethodItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (ejbItemProvider != null) ejbItemProvider.dispose();
		if (layerSegmentItemProvider != null) layerSegmentItemProvider.dispose();
		if (dtoItemProvider != null) dtoItemProvider.dispose();
		if (storeItemProvider != null) storeItemProvider.dispose();
		if (uiItemProvider != null) uiItemProvider.dispose();
		if (layerItemProvider != null) layerItemProvider.dispose();
		if (restEntityItemProvider != null) restEntityItemProvider.dispose();
		if (facadeItemProvider != null) facadeItemProvider.dispose();
		if (warItemProvider != null) warItemProvider.dispose();
		if (componentItemProvider != null) componentItemProvider.dispose();
		if (relationArchItemProvider != null) relationArchItemProvider.dispose();
		if (arquitectureMetamodelItemProvider != null) arquitectureMetamodelItemProvider.dispose();
		if (containersItemProvider != null) containersItemProvider.dispose();
		if (pojoItemProvider != null) pojoItemProvider.dispose();
		if (servicesItemProvider != null) servicesItemProvider.dispose();
		if (metamodelItemProvider != null) metamodelItemProvider.dispose();
		if (readItemProvider != null) readItemProvider.dispose();
		if (createItemProvider != null) createItemProvider.dispose();
		if (saleItemProvider != null) saleItemProvider.dispose();
		if (exchangeItemProvider != null) exchangeItemProvider.dispose();
		if (compositionItemProvider != null) compositionItemProvider.dispose();
		if (operationsItemProvider != null) operationsItemProvider.dispose();
		if (moduleItemProvider != null) moduleItemProvider.dispose();
		if (specialEntityItemProvider != null) specialEntityItemProvider.dispose();
		if (generalEntityItemProvider != null) generalEntityItemProvider.dispose();
		if (entityItemProvider != null) entityItemProvider.dispose();
		if (relationDomItemProvider != null) relationDomItemProvider.dispose();
		if (transactionItemProvider != null) transactionItemProvider.dispose();
		if (submoduleItemProvider != null) submoduleItemProvider.dispose();
		if (domainMetamodelItemProvider != null) domainMetamodelItemProvider.dispose();
		if (actionDispatcherItemProvider != null) actionDispatcherItemProvider.dispose();
		if (routerItemProvider != null) routerItemProvider.dispose();
		if (jsonItemProvider != null) jsonItemProvider.dispose();
		if (mdItemProvider != null) mdItemProvider.dispose();
		if (cssItemProvider != null) cssItemProvider.dispose();
		if (apiCallItemProvider != null) apiCallItemProvider.dispose();
		if (directoryItemProvider != null) directoryItemProvider.dispose();
		if (stateItemProvider != null) stateItemProvider.dispose();
		if (uiFrontItemProvider != null) uiFrontItemProvider.dispose();
		if (visualizerItemProvider != null) visualizerItemProvider.dispose();
		if (designItemProvider != null) designItemProvider.dispose();
		if (actionCreatorItemProvider != null) actionCreatorItemProvider.dispose();
		if (routerComponentItemProvider != null) routerComponentItemProvider.dispose();
		if (containerItemProvider != null) containerItemProvider.dispose();
		if (servicesFrontItemProvider != null) servicesFrontItemProvider.dispose();
		if (functionalityItemProvider != null) functionalityItemProvider.dispose();
		if (jsItemProvider != null) jsItemProvider.dispose();
		if (actionItemProvider != null) actionItemProvider.dispose();
		if (reduxItemProvider != null) reduxItemProvider.dispose();
		if (reactAppItemProvider != null) reactAppItemProvider.dispose();
		if (fileItemProvider != null) fileItemProvider.dispose();
		if (componentFrontItemProvider != null) componentFrontItemProvider.dispose();
		if (reducerItemProvider != null) reducerItemProvider.dispose();
		if (moduleFrontItemProvider != null) moduleFrontItemProvider.dispose();
		if (technologyMetamodelItemProvider != null) technologyMetamodelItemProvider.dispose();
		if (javaAppItemProvider != null) javaAppItemProvider.dispose();
		if (jeE_ProjectItemProvider != null) jeE_ProjectItemProvider.dispose();
		if (nativeClassItemProvider != null) nativeClassItemProvider.dispose();
		if (eInterfaceItemProvider != null) eInterfaceItemProvider.dispose();
		if (libraryItemProvider != null) libraryItemProvider.dispose();
		if (attributeItemProvider != null) attributeItemProvider.dispose();
		if (genericClassItemProvider != null) genericClassItemProvider.dispose();
		if (methodBackItemProvider != null) methodBackItemProvider.dispose();
		if (abstractClassItemProvider != null) abstractClassItemProvider.dispose();
		if (epackageItemProvider != null) epackageItemProvider.dispose();
		if (eClassItemProvider != null) eClassItemProvider.dispose();
		if (annotationItemProvider != null) annotationItemProvider.dispose();
		if (subprojectItemProvider != null) subprojectItemProvider.dispose();
		if (descriptorItemProvider != null) descriptorItemProvider.dispose();
		if (javaScriptItemProvider != null) javaScriptItemProvider.dispose();
		if (utilItemProvider != null) utilItemProvider.dispose();
		if (reducersItemProvider != null) reducersItemProvider.dispose();
		if (actionsItemProvider != null) actionsItemProvider.dispose();
		if (backItemProvider != null) backItemProvider.dispose();
		if (frontItemProvider != null) frontItemProvider.dispose();
		if (propertyItemProvider != null) propertyItemProvider.dispose();
		if (abstractMethodItemProvider != null) abstractMethodItemProvider.dispose();
	}

}
